title: Siddhartha Ghosh | Cloud, Networking, AI and Infrastructure Blogs

description: >-
  Technical blogs on Azure, Kubernetes, Terraform, Networking, PowerShell,
  AI, Machine Learning, Infrastructure Design, Cisco, NSX and Cloud
  Architecture by Siddhartha Ghosh.

permalink: /:title/

baseurl: ""
url: "https://web.techmaker.in"
site-twitter: ""

# Author Settings
author: Siddhartha Ghosh # add your name
author-img: Siddhartha.jpeg # add your photo
about-author: I’m a technical enthusiast and technology professional passionate about exploring how modern systems work across cloud, AI, networking, and beyond. Through my blogs, I share practical insights, real-world examples, and hands-on concepts that bring technology to life.   # add description
social-twitter: # add your Twitter handle
social-facebook: siddhartha.ghosh1981 # add your Facebook handle
social-github: siddhartha2303 # add your Github handle
social-linkedin: sighosh # add your Linkedin handle
social-email: siddhartha.ghosh@hotmail.com # add your Email address

# Disqus
discus-identifier: disqus_Zrh3aqjaEw # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
